version: "3.4"

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:1389 -t 900 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
      - config.env
      - pf.env
    ports:
      - 443:9031
      - 9999:9999
    networks:
      - pingnet-internal
    cap_add:
      - NET_ADMIN
    volumes:
       - ../server_profiles/pingfederate:/opt/in
#      - ./licenses/pingfederate.lic:/opt/in/instance/server/default/conf/pingfederate.lic

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - MAKELDIF_USERS=10
      - MAX_HEAP_SIZE=768m
    env_file:
      - ~/.pingidentity/devops
      - config.env
    ports:
      - "3389:1389"
      - "3443:1443"
      - 3636:1636
      - 1636:1636
      - 1443:1443
      - 389:1389
    expose:
      - 443
      - 1443
      - 3443
      - 389
      - 3389
      - 636
      - 3636
    volumes:
       - ../server_profiles/pingdirectory:/opt/in
#       - ./licenses/PingDirectory.lic:/opt/licenses/PingDirectory.lic
    networks:
      - pingnet-internal

  pingdatasync:
    image: pingidentity/pingdatasync:edge
    command: wait-for pingdirectory:1389 -t 300 -- entrypoint.sh start-server
#    environment:
#      - LICENSE_DIR=/opt/licenses
#      - LICENSE_FILE_NAME=PingDirectory.lic
#      - MUTE_LICENSE_VERIFICATION=true
#      - SERVER_PROFILE_PATH=server_profiles/pingdatasync
    env_file:
      - ${HOME}/.pingidentity/devops
      - config.env
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "2636:636"
      - "2443:443"
    volumes:
       - ../server_profiles/pingdatasync:/opt/in
#      - ./licenses/PingDirectory.lic:/opt/licenses/PingDirectory.lic
    networks:
      - pingnet-internal

networks:
    pingnet-internal:
